"""
models.py
---------
Pydantic v2 data models for an AI reinforcement learning environment.

Defines the core structures for agent actions, model responses,
environment observations, and scalar reward signals.
"""

from typing import List, Literal, Optional

from pydantic import BaseModel, Field, model_validator


class Action(BaseModel):
    """Represents an action taken by the agent within the environment.

    Attributes:
        type: The kind of action to perform.
        query: Required for 'submit_query', 'refine_query'.
        selected_index: Required for 'select_response'.
        score: Required for 'rate_response'.
        plan: Required for 'plan_task'.
    """

    type: Literal[
        "submit_query",
        "select_response",
        "rate_response",
        "refine_query",
        "plan_task",
        "compare_responses",
        "summarize"
    ]
    query: Optional[str] = Field(default=None, description="Query text for submission.")
    selected_index: Optional[int] = Field(default=None, ge=0, description="Selected response index.")
    score: Optional[float] = Field(default=None, ge=0.0, le=1.0, description="Quality rating.")
    plan: Optional[str] = Field(default=None, description="Plan details for plan_task.")

    @model_validator(mode="after")
    def _validate_fields(self) -> "Action":
        if self.type in ("submit_query", "refine_query") and not self.query:
            raise ValueError(f"query is required for {self.type}")
        if self.type == "select_response" and self.selected_index is None:
            raise ValueError("selected_index is required for select_response")
        if self.type == "rate_response" and self.score is None:
            raise ValueError("score is required for rate_response")
        if self.type == "plan_task" and not self.plan:
            raise ValueError("plan is required for plan_task")
        return self


class Response(BaseModel):
    """A single candidate response generated by the AI system.

    Attributes:
        text: The raw response text returned by the model.
        relevance: Estimated relevance of the response to the query,
            in the closed interval [0, 1].
        confidence: Model's self-reported confidence in the response,
            in the closed interval [0, 1].
    """

    text: str = Field(..., min_length=1, description="Response text produced by the model.")
    relevance: float = Field(..., ge=0.0, le=1.0, description="Relevance score in [0, 1].")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score in [0, 1].")


class Observation(BaseModel):
    """A snapshot of the environment state returned to the agent after each step.

    Attributes:
        responses: Ordered list of candidate responses available for evaluation
            or selection.
        history: Chronological list of prior queries or interaction turns,
            used to provide conversational context.
    """

    responses: List[Response] = Field(default_factory=list, description="Candidate responses from the current step.")
    history: List[str] = Field(default_factory=list, description="Ordered list of past query strings or turn summaries.")


class Reward(BaseModel):
    """Scalar reward signal emitted by the environment after an agent action.

    Attributes:
        value: The numeric reward. Positive values indicate beneficial actions;
            negative values indicate harmful or suboptimal ones. The scale is
            task-dependent and not bounded by default.
    """

    value: float = Field(..., description="Scalar reward value returned by the environment.")